### ISSUE TITLE
feat: add generic schema fields handling to `QriDataset`

### ISSUE THREAD

**Issue by osterbit** [qri-io/qri-python#6]
- set a class attribute `fields` that allows for more pythonic interaction with dataset schema
  - allow for nested fields to exist in both a py-dict format and a pandas dataframe format (using `pd.io.json.json_normalize(d)` where d is the py-dict
- add a rename method that updates the dataframe field, the py-dict, and the structure's field title

**Comment by orblivion** [comment]
If I understood correctly during the Building Qri meeting, this issue is outdated given the current state of the Python client. Is that right? @b5 @dustmop (If so, I just wanted to leave an artifact for others).

**Comment by dustmop** [comment]
Yes, correct. I hadn't spent enough time to verify, but looking at it now, the problem it's referring to, that the schema isn't directly accessible, is no longer the case since the recent rewrite. I'll close the issue.
